# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(upload_to=b'')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
